-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: check-ast
    -   id: check-symlinks
    -   id: name-tests-test
        exclude: tests/util
    -   id: flake8
        args: ['--ignore=E501']
